### ISSUE TITLE
Arguments Type Error

### ISSUE THREAD

**Issue by Aguias1** [martin-wey/CodeUltraFeedback#1]
https://github.com/martin-wey/CodeUltraFeedback/blob/b8c954dca0d549e19b2658c8bd5b5810f8edc31e/src/utils/config.py#L72

I think this is a float and not an integer.

**Comment by martin-wey** [comment]
Thanks for reporting this issue. Just made the change.

**Comment by Aguias1** [comment]
top_p is also.
