### ISSUE TITLE
How to train

### ISSUE THREAD

**Issue by renmengjie7** [martin-wey/CodeUltraFeedback#2]
How to use your code in `src/dpo` to train model ? Can you provide an example script ?

**Comment by martin-wey** [comment]
Hi, we will soon add a detailed readme on how to run the scripts.

To train a model using DPO: 
```sh
export PYTHONPATH=$PYTHONPATH:$(pwd)
python src/dpo/run_dpo.py src/dpo/recipes/config_qlora_dpo_codellama_base.yaml
```
You can check for all the arguments in the [config_qlora_dpo_codellama_base.yaml](https://github.com/martin-wey/CodeUltraFeedback/blob/main/src/dpo/recipes/config_qlora_dpo_codellama_base.yaml) file. If you have your own model checkpoint locally, you can run: 
```sh
python src/dpo/run_dpo.py src/dpo/recipes/config_qlora_dpo_codellama.yaml \
  --model_name_or_path={path_to_your_model_checkpoint}
```
Make sure to change the `chat_template` argument accordingly, depending on your model type/family :)

SFT training works similarly with the recipe file [config_qlora_sft_codellama.yaml](https://github.com/martin-wey/CodeUltraFeedback/blob/main/src/dpo/recipes/config_qlora_sft_codellama.yaml).

**Comment by renmengjie7** [comment]
Thank you very much for your quick reply !
