### ISSUE TITLE
CODAL-bench evaluation

### ISSUE THREAD

**Issue by hrshtv** [martin-wey/CodeUltraFeedback#4]
Hi,
Thanks for your work on this project!    
I’m trying to evaluate a model on CODAL-bench, but I couldn’t find any instructions for doing so in the README. There are two files that seem relevant — generate_responses.py and generate_ratings.py — but I’m unsure what arguments need to be passed when running these. Could you please clarify?  
Additionally, I noticed that in the `load_model_and_tokenizer` function, there doesn’t seem to be an option to load a HuggingFace model in FP32 or BF16 precision. Is this intentional? The current code only seems to support only FP16 when `model_args.model_name_or_path` contains “GPTQ” and INT4 when `model_args.model_name` includes “-sft” or “-dpo.”   
Given this, could you provide details (precision used, etc.) about how the numbers in Table 4 of the paper were computed for models like DeepSeek-Coder-6.7B-Instruct?

**Comment by martin-wey** [comment]
Hi, thanks for raising this issue. I hope the following answers all your questions.

> I’m trying to evaluate a model on CODAL-bench, but I couldn’t find any instructions for doing so in the README. There are two files that seem relevant — generate_responses.py and generate_ratings.py — but I’m unsure what arguments need to be passed when running these. Could you please clarify?

Your intuition is right :) 
To evaluate an LLM on the benchmark, you first need to generate responses to the benchmark's instructions, then evaluate the responses using a judge. To generate the responses, run:
```
python src/evaluate/generate_responses.py src/evaluate/recipes/config_gen_codellama_yaml \
  --model_name_or_path={path_to_your_model_checkpoint} \
  --model_name={your_model_name} \
  --output_dir=./results/
```
You can replace `src/evaluate/recipes/config_gen_codellama_yaml` with a yaml file containing your script arguments.

Next, you need to run a judge LLM to obtain the scores. You can use OpenAI models or open-weight models for judging:
```
python src/evaluate/generate_ratings.py \
  --dataset_name_or_path=./datasets/codal-bench \
  --dataset_split=test \
  --model_responses_dir=./results/ \
  --model_judge=gpt-3.5-turbo \
  --model_reference=gpt-4-turbo \
  --model_test=codellama-7b-instruct-sft
```
Note that `--model_reference` is the reference response used during judgement (as explained in the paper). The current version of the benchmark supports `gpt-3.5-turbo`, `gpt-4-turbo`, and `claude-3-sonnet-20240229`. 

> Additionally, I noticed that in the load_model_and_tokenizer function, there doesn’t seem to be an option to load a HuggingFace model in FP32 or BF16 precision. Is this intentional? The current code only seems to support only FP16 when model_args.model_name_or_path contains “GPTQ” and INT4 when model_args.model_name includes “-sft” or “-dpo.”

You may change the `torch_dtype` parameter to load the model in bfloat16 if that's more convenient for you. We tune the model using SFT/DPO with 4-bit QLoRA and unsloth and load them accordingly for inference. 

> Given this, could you provide details (precision used, etc.) about how the numbers in Table 4 of the paper were computed for models like DeepSeek-Coder-6.7B-Instruct?

The script `src/evaluate/show_metrics.py` outputs the average score per preference for a given LLM. The following is the result when using GPT-3.5-Turbo as a judge with its own responses as references:
![image](https://github.com/user-attachments/assets/cb92aa6d-fd4c-44af-935c-29bf4706f3b3)

I am currently working on the full replication package for the paper, which will include all the LLMs and judges outputs. 
Please, let me know if you need more help!

**Comment by hrshtv** [comment]
Thanks for sharing this!
